"""Initial migration

Revision ID: b387298a42e2
Revises: 
Create Date: 2025-01-20 02:32:09.204410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b387298a42e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
